window.cmp_config_data_cs="BPB3DiwPB3DiwAfbpBDEDXAAAAAdCADAAaACAA6A";
window.cmp_config_data={"intID":21769,"uid":13727,"cookiefree":0,"savepref":0,"lvt":-1,"bnc":0,"bnc2":0,"bncd":9414,"iabid":31,"host":"consentmanager.mgr.consensu.org","host2":"www.consentmanager.net","cdn":"cdn.consentmanager.mgr.consensu.org","logo":"https:\/\/cdn.consentmanager.mgr.consensu.org\/delivery\/cmplogo.svg","logow":"16","logoh":"16","cmpname":"consentmanager.net","iuid":"","tcfversion":0,"setuniqueid":0,"consentscope":1,"cookiescope":0,"scopeid":0,"boolNoCMPLogo":"0","disablevendorswopurpose":0,"turnoffvendorswopurpose":0,"turnonvendorswopurpose":0,"disablevendorswopurposeall":0,"turnoffvendorswopurposeall":1,"turnonvendorswopurposeone":1,"hidevendortoggles":0,"hidevendors":0,"regulation":1,"strSetFixedLanguage":"DE","defaultlang":"EN","boolCustomPurposeDefault":"0","boolCustomVendorsDefault":"0","enableRecallBtn":"1","ccpaRecallBtn":"0","rowRecallBtn":"0","oob":"0","welcomeprps":"1","welcomeprpsccpa":"0","islspa":0,"ccpavm":0,"boolGroupChoices":"1","intVersion":"7","intDesignVersion":"2","verifyage":"0","simplecookie":"0","recallIcon":"\/delivery\/cmplogo.svg","menu_vendors":0,"menu_privacy":0,"togglesinmenu":0,"custheadlineontop":0,"togglechange":0,"boolShowAllPurposeBtnTop":"1","boolShowAllPurposeBtnBottom":"0","boolShowAllVendorsBtnTop":"1","boolShowAllVendorsBtnBottom":"0","cookielist":"1","intAskAgainForNewVendorsDays":"14","intAskAgainDaysForRejectedUsers":"14","intAskAgainDaysForAcceptedUsers":"365","strLogoUrl":"https:\/\/cdn.consentmanager.mgr.consensu.org\/delivery\/img\/logo1608566886x6036.gif","strLogoClick":"https:\/\/tableware24.com","tac":{"DE":"https:\/\/tableware24.com\/agb\/"},"imp":{"DE":"https:\/\/tableware24.com\/impressum\/"},"policytype":0,"strPolicyURL":"https:\/\/tableware24.com\/datenschutz\/","strPolicyURLlang":"DE","ccpadnslogic":0,"ccpadns":"https:\/\/...","design_intID":1,"design_intPosition":"3","design_boolGrayOutWebsite":"0","design_intGrayOutClickBehavior":"0","design_intCloseClickBehavior":"0","design_toggle":3,"design_toggletxt":1,"design_listicon":0,"design_intScrollBehavior":"0","design_intScrollDepth":"100","design_intNavigateBehavior":"0","design_boolShowCountdown":"0","design_intCountdownTime":"45","design_intCountdownBehavior":"0","design_btns":0,"design_custombtns":0,"tcfcompliant":0,"strCustomCSS":"","strWebsite":"tableware24.com","verGVLv1":215,"verGVLv2":78,"pubcc":"EU","compresscookie":1,"storecookie":1,"storels":0,"showCompany":0,"c_name":"unkown","c_addr1":"0","c_addr2":"0","c_zip":"0","c_place":"0","c_country":"0","c_tel":"","c_mail":"j.stub@tableware24.com","c_url":"","c_descr":[],"d_name":"","d_mail":"","d_tel":"","d_url":"","vendors":[],"cvc":"____","purposes":[{"id":"51","wsid":"21769","n":"Funktion","t":"2","cp":",,","up":",,"},{"id":"52","wsid":"21769","n":"Marketing"}],"stacks":[],"cpc":"____","ccc":"aBPB3DiwgAwAzADQBYAAIABwAFgAOgAuADAAGgAPAAoABiAD4AQ4DgwHEgPLAeiBB0CJIFTgK-AWzAuABdQAEQfo","usps":"1---","separateli":0};
if(!("cmp_scripts" in window)){window.cmp_scripts = [];}
if(!("cmp_scripturls" in window)){window.cmp_scripturls = [];}
if(!("cmp_proto" in window)){window.cmp_proto = "https:";}
function cmp_loadCS(){var l=0;var k=[]; for(var i=0;i<window.cmp_scripts.length;i++){if(window.cmp_scripts[i].substr(0,1)!="#"){l++; k.push(window.cmp_scripturls[i]);}} var lx = false; if("cmpmngr" in window){if(l>0){if(!("cmp_timer" in window)){window.cmp_timer = new Date();} var now = new Date(); if((now.getTime() - window.cmp_timer.getTime()) > 3000){for(var kx=0; kx<k.length; kx++){cmp_append_script2(k[kx],"");}}if((now.getTime() - window.cmp_timer.getTime()) > 8000){lx = true;}}else{lx=true;}}
  if(lx){window.cmpmngr.loadSettings(window.cmp_config_data_cs,{},window.cmp_config_data);}else{window.setTimeout("cmp_loadCS()",30);}
 };
function cmp_append_script(s,r){window.cmp_scripts.push(r);window.cmp_scripturls.push(s);cmp_append_script2(s,r);}function cmp_append_script2(s,r){var o=document.createElement("script");o.async=true;o.type="text/javascript";o.setAttribute("data-cmp-ab","1");o.src=s;if(document.body){document.body.appendChild(o);}else if(document.currentScript){document.currentScript.parentElement.appendChild(o);}else{var s = document.getElementsByTagName("script");s = s[s.length - 1];s.parentElement.appendChild(o);}}
cmp_append_script(window.cmp_proto+"//cdn.consentmanager.mgr.consensu.org/delivery/customcss/9414_21769_1.v2.js","css");
cmp_append_script(window.cmp_proto+"//cdn.consentmanager.mgr.consensu.org/delivery/customvendors/21769_1.js","vendors");

cmp_loadCS();